services:
  alubassa:
    container_name: alubassa
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3015:3000"
    networks:
      - caddy-network

networks:
  caddy-network:
    driver: bridge
    attachable: true
# networks:
#   frostNet:
#     external: true
# networks:
#   frostNet:
#     driver: bridge
#     attachable: true
# correct deployment
