services:
  wintercode:
    container_name: wintercode
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ../shared/.env.prod
    volumes:
      - /home/wintercode/backup/wintercode:/app/uploads
    ports:
      - "4000:4000"
    networks:
      - caddy-network

networks:
  caddy-network:
    driver: bridge
    attachable: true
# networks:
#   frostNet:
#     external: true
# networks:
#   frostNet:
#     driver: bridge
#     attachable: true
# correct deployment
