services:
  alubassa:
    container_name: alubassa
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3015:3000"
    networks:
      - caddy-net

networks:
  caddy-net:
    external: true
# networks:
#   frostNet:
#     external: true
# networks:
#   frostNet:
#     driver: bridge
#     attachable: true
# correct deployment
